### ISSUE TITLE
more specific dependencies

### ISSUE THREAD

**Issue by GR-ray** [XuelianCheng/SLT-Net#10]
When I run PVTV2_ After TEM. py, the following error occurred:

Traceback (most recent call last):
  File "/media/estar/Data1/gr/SLT-Net-master/lib/pvtv2_afterTEM.py", line 280, in <module>
    net = Network(pvtv2_pretrained=False).cuda()
  File "/media/estar/Data1/gr/SLT-Net-master/lib/pvtv2_afterTEM.py", line 269, in __init__
    self.feat_net = FeatureExtraction(self.channel, self.pvtv2_pretrained, self.imgsize)
  File "/media/estar/Data1/gr/SLT-Net-master/lib/pvtv2_afterTEM.py", line 173, in __init__
    self.pvtv2_en = create_model('pvt_v2_b5',
  File "/home/estar/anaconda3/envs/STL-Net/lib/python3.8/site-packages/timm/models/factory.py", line 71, in create_model
    model = create_fn(pretrained=pretrained, pretrained_cfg=pretrained_cfg, **kwargs)
  File "/media/estar/Data1/gr/SLT-Net-master/lib/pvt_v2.py", line 387, in pvt_v2_b5
    model = PyramidVisionTransformerV2(
TypeError: __init__() got an unexpected keyword argument 'pretrained_cfg'

I guess this may be caused by a mismatch in the version of **timm**, so can you provide more specific dependencies.

**Comment by alessandriniluca** [comment]
I am facing the same problem. Have you found a solution for that?

**Comment by Garyson1204** [comment]
timm==0.4.12 works. @RuiGao7 @alessandriniluca
